DROP DATABASE IF EXISTS Readit_db;
CREATE DATABASE Readit_db;
USE Readit_db;
CREATE TABLE books(
 id INTEGER(11) AUTO_INCREMENT NOT NULL,
 authorId INTEGER(11),
 title VARCHAR(100),
  genre VARCHAR(50) NULL,
 PRIMARY KEY (id)
);
